### ISSUE TITLE
Docker Image instead of installtion

### ISSUE THREAD

**Issue by Vad1mo** [moncho/dry#33]
Its quite handy if dry would be also available as a docker image so one can create an alias and use it without installing it.

**Comment by moncho** [comment]
Hey, 

Somebody created a Dockerfile some time ago, please check https://hub.docker.com/r/kkessler/docker-dry/

**Comment by Vad1mo** [comment]
I just tried to build a new image and make a contribution.

When I do
```
➜  OSS docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock dry dry

panic: runtime error: slice bounds out of range

                                               goroutine 33 [running]:
                                                                      panic(0x8a7fa0, 0xc42000c0d0)
                                                                                                        /usr/local/go/src/
runtime/panic.go:500 +0x1a1
                           github.com/moncho/dry/appui.(*DockerPs).containerInformation(0xc4203c0840, 0xc420326f00, 0xc420
043c30)
        /go/src/github.com/moncho/dry/appui/ps.go:115 +0x257
                                                            github.com/moncho/dry/appui.(*DockerPs).containerTable(0xc4203
c0840, 0x97f460, 0xc4203c0888)
                                /go/src/github.com/moncho/dry/appui/ps.go:97 +0x1c0
                                                                                   github.com/moncho/dry/appui.(*DockerPs)
.Render(0xc4203c0840, 0x0, 0x0)
                                /go/src/github.com/moncho/dry/appui/ps.go:84 +0x8a
                                                                                  github.com/moncho/dry/ui.(*Screen).Rende
rRenderer(0xc420050640, 0x7, 0xb93200, 0xc4203c0840)
                                                        /go/src/github.com/moncho/dry/ui/screen.go:205 +0x31
                                                                                                            github.com/mon
cho/dry/app.Render(0xc420336800, 0xc420050640, 0xc4203c4900)
                                                                /go/src/github.com/moncho/dry/app/render.go:148 +0x5a5
                                                                                                                      gith
ub.com/moncho/dry/app.RenderLoop.func1(0xc4203c0c00, 0xc420050640, 0xc420336800, 0xc4203c4900)
```

After trying this I thought well it is probably an problem with alpine, so let build everything from scratch

```
FROM golang:1.7-alpine

WORKDIR /root

RUN apk --no-cache add wget openssl ca-certificates git && \  
    wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -O glide.tar.gz && \
        tar -xzf glide.tar.gz && mv linux-amd64/glide /go/bin/glide && \
    go get github.com/moncho/dry && \
    cd $GOPATH/src/github.com/moncho/dry && \
    glide install  && \
    go build && \
    mv dry /usr/local/bin/dry

CMD ["/usr/local/bin/dry"]
```

Now comes the  part I don't understand
When I start the container with  `docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock dry` the above error is displayed but when I **enter**(sh) into the container instead of starting dry `docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock dry sh` I can start dry and it works as expected.

**Comment by moncho** [comment]
Ugh, not nice, **dry**!

The root cause of the problem is that for some reason terminal dimensions (height and width) are not being retrieved when doing a docker run, one of the consequences being the panic attack.

I will add some checks to avoid panicking, but it will not solve the real problem. For this I need some thinking to figure out how/if it can be solved.

If anybody is curious the actual code that gets terminal dimension can be found [here](https://github.com/nsf/termbox-go/blob/master/termbox.go). 

Help and ideas are much appreciated :)

**Comment by Vad1mo** [comment]
How are your friends like [dockly ](https://github.com/lirantal/dockly), [sen](https://github.com/TomasTomecek/sen) or ctop doing it?

**Comment by moncho** [comment]
Good question. 

Ctop is the closest thing, it uses gizak/termui which is based on nsf/termbox-go, which is what dry uses to get terminal dimensions. But it is a good starting point, thanks.

**Comment by moncho** [comment]
There is an open issue in the Docker repo [#25450](https://github.com/docker/docker/issues/25450 ) that explains **dry** behaviour when it is run inside a container. Real terminal dimensions are set late in the process of running a container using the` -i ` option, and **dry** relies on the width and height of the terminal to render stuff.

It is timing issue, which explains why other similar tools do not have the problem (although are probably not safe from it). 

The fix is label for **Docker** 1.14, as a workaround until then I would suggest to add a `sleep 1` to the CMD instruction on the Dockerfile, to give time to Docker to set terminal dimensions.

**Comment by moncho** [comment]
I have added a Dockerfile to the repo and created an image on the Docker hub, to use it:
```docker run -it -v /var/run/docker.sock:/var/run/docker.sock moncho/dry```

@Vad1mo Could you please give it a try and let know if you find any issues?

**Comment by Vad1mo** [comment]
works perfectly! thank you.


btw. I would change the Dockerfile to 
`RUN apk --no-cache update && apk add curl file` 

or use wget as it is already part of busybox that alpine is using.

**Comment by moncho** [comment]
Ah yes, I will add the ` --no-cache`, thanks.

Curl and file are needed by the **dryup.sh** script used to install dry, which is is a convenient way to install it.
