### ISSUE TITLE
Broken output rendering

### ISSUE THREAD

**Issue by wyqydsyq** [moncho/dry#59]
See attached screenshot, the layout is all mutilated and I get a bunch of question marks "�"

Using:
OS: `OpenSUSE TumbleWeed`
Gnome: `3.26.1`
Docker: `version 17.09.1-ce, build f4ffd2511ce9`

![image](https://user-images.githubusercontent.com/621277/36133748-f10a35fe-10cb-11e8-84d8-b084170a93c4.png)

**Comment by wyqydsyq** [comment]
This only occurs when using the native version from the install bash script, when I use it via Docker it renders fine.

Seems there's some external dependency that isn't mentioned in the readme and is not installed in my host OS?

**Comment by moncho** [comment]
Hey, thanks for reporting!!!

It might be related to your terminal capabilities. Could you please post here the result of running `echo $TERM`?

Also, it might be helpful to run **dry**  with `TERM=xterm dry` and see if it fixes the problem.

**Comment by wyqydsyq** [comment]
My `$TERM=xterm-256color`, I'm using the Tilix emuilator and Fish shell.

Using `TERM=xterm dry` works, I'm not sure why `xterm-256color` doesn't because as far as I know it's basically a superset/extension of `xterm` with moe colors?

**Comment by moncho** [comment]
I would say it is related to [this bug](https://bugzilla.opensuse.org/show_bug.cgi?id=1054448) in Tumbleweed, not the part about ncurses (which **dry** does not use) but the part about **terminfo**.

I prefer to wait and see what happens before really looking at changing anything, because:
- it might be an OpenSuse problem that will get fixed eventually,
- or it might be a change in terminfo and the problem will show up in other distros, in this case changes in one of the Go libraries that **dry** uses, [termbox-go](https://github.com/nsf/termbox-go) will have to be done.

Alternative ideas are very welcome, of course :)

**Comment by wyqydsyq** [comment]
That particular issue seems to be the opposite of what I'm experiencing here:
> Launching yast in xterm results in broken rendering of UI elements.
Curiously, if environment variable TERM is set to something other than xterm, yast will render properly.

For me `xterm-256color` is broken but `xterm` itself works fine, so does `xterm-color`.

But after reading that I thought I'd try some another ncurses app (ngrok) with `xterm-256color` and found it too was broken in a similar way, so I would put this down to being an issue with OpenSUSE unless people begin to have it using `xterm-256color` in other Linux distributions.

I'll close this issue and open one on the OpenSUSE bug tracker since it seems to be distro-specific, but if anyone is experiencing this on another distro it should probably be reopened here.

**Comment by thatside** [comment]
Had the same issue on Manjaro with Guake + Byobu today. My `$TERM` is `screen-256color.` The solution with `TERM=xterm dry` works well for me.
